spring:
  datasource:
    username: root
    password: qwertylol
    url: jdbc:postgresql://localhost:5432/products
    driver-class-name: org.postgresql.Driver
    initialization-mode: ALWAYS
    schema: classpath*:src/main/resources/database/initDB.sql
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

